name: ASCII
on: push

jobs: 
    # all the jobs will run parallel on different machines and will not wait for anbody ...this is the default behavior of github action 
    build_ascii:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program 
          run: sudo apt-get install cowsay -y 
        - name: Execute cowsay CMD
          run: cowsay -f "BLAA BLAA ------">dragon.txt
        - name: sleep 
          run: sleep 30
    test_ascii:
        runs-on: ubuntu-latest
        steps:
        - name: sleep
          run: sleep 30
        - name: Test the Dragon file 
          run: grep -i "BLAA" dragon.txt
    deploy_ascii:
        runs-on: ubuntu-latest
        steps:
        - name: open the file dragon 
          run: cat dragon.txt
        - name: deploying
          run: echo deploying ----