name: Docker_Build_And_Push

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKERHUB_USERNAME: gillnavi

concurrency: 
  group: unilink-${{ github.ref }}
  cancel-in-progress: true

jobs: 
    Build_Push:
        strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
            directory: [client, server]
            image_name: [client_image, server_image]
            exclude:
              - image_name: client_image
                directory: server
              - image_name: server_image
                directory: client
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
        - name: Welcome
          run: echo "Starting build for ${{ matrix.directory }} triggered by ${{ github.actor }} on event ${{ github.event_name }}" # using the github context 

        - name: runner information 
          run: |
               ehco "Runner OS ${{runner.OS}}"
               echo "Runner Name  ${{runner.name}}"
               ehco "Runner Arch ${{runner.arch}}"
        - name: Checkout the Repository
          uses: actions/checkout@v4

        - name: Checking the repository contents
          run: ls -ltr

        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

        - name: Build the Docker Image
          run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest ./${{ matrix.directory }}

        - name: Push the Docker Image to Docker Hub
          run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest
