name : Demo WorkFlow

on : push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "welcome to ubuntu "
        - name: list files 
          run: ls
        - name: cloning the project
          run: git checkout https://github.com/navigill7/UniLink 
        - name: Reading Files from the project 
          run: cd client