name: Demo WorkFlow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Welcome Message
        run: echo "Welcome to Ubuntu"

      - name: List and Read files
        run: | 
             ls -ltra
             cat package-lock.json
        working-directory: client
      - name : installing cowsay 
        run: sudo apt-get install cowsay -y 
      - name: Generate the ASCII ArtWork
        run: cowsay -f dragon "BLAA.....Blaa " >> dragon.txt

      - name: testing if the file exists
        run: grep -i "dragon" dragon.txt

      - name: read the dragon file
        run: cat dragon.txt
      
      - name: List repo
        run: ls -ltra
      # - name: List Files
      #   run: ls

      # - name: Reading Files from the Project
      #   run: ls
      #   working-directory: client 

      
