name: Demo WorkFlow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Welcome Message
        run: echo "Welcome to Ubuntu"

      - name: List Files
        run: ls

      - name: Reading Files from the Project
        run: ls
        working-directory: client 
